config/routes.rb
KrutmanApp::Application.routes.draw do
  resources :users do
    member do #метод member означает, что маршруты отвечают на URL, содержащие id пользователя. Метод collection работает без id
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/views/shared/_delete_link.html.erb
<%= link_to "delete", object, method: :delete,
                                 data: { confirm: "You sure?" },
                                 title: object.content %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <div class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </div>
  <div class="content">
    <%= feed_item.content %>
    <%= image_tag feed_item.picture.url if feed_item.picture? %>
  </div>
  <div class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </div>
  <% if current_user?(feed_item.user) %>
    <%= render 'shared/delete_link', object: feed_item %>
  <% end %>
</li>

app/views/shared/_homepage.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to the Krutman App</h1>
  <p>This is the home page for me.</p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
      <%= f.text_area :content, placeholder: "Compose new micropost...", class: "form-control", style: "resize:none", rows: "5" %>
  </div>
  <div class="form-group">
     <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  </div>
  <span class="picture">
	<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_homepage.html.erb
<div class="row">
	<aside class="col-md-4">
	  <section class="user_info">
	    <%= render 'shared/user_info' %>
	  </section>
	  <section>
	    <%= render 'shared/stats' %>
	  </section>
	  <section class="micropost_form">
	    <%= render 'shared/micropost_form' %>
	  </section>
	</aside>
	<div class="col-md-8">
	  <h3>Micropost Feed</h3>
	  <%= render 'shared/feed' %>
	</div>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<div>
  <%= link_to "view my profile", current_user %>
</div>
<div>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</div>